name: ❓ Question / Help
description: Ask a question or get help
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please check our [documentation](https://github.com/suryanshp1/code-reviewer-ci/blob/main/README.md) first.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Setup & Installation
        - Configuration
        - GitHub Actions Integration
        - Hugging Face Deployment
        - LLM Configuration
        - Code Review Behavior
        - Performance/Optimization
        - Troubleshooting
        - Best Practices
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide relevant context about your setup or situation
      placeholder: |
        I'm using...
        I want to achieve...
        I've tried...

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What steps have you already taken to solve this?
      placeholder: |
        - Checked the README
        - Searched existing issues
        - Tried configuration X

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked the documentation
          required: true
        - label: I have searched for similar questions
          required: true
